# Target specific macros
TARGET = CleverCLF
TARGET_SOURCES = \
	lineFollower.c \
	functions.c
TOPPERS_OSEK_OIL_SOURCE = ./lineFollower.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
