# Target specific macros
TARGET = line_OSEK
TARGET_SOURCES = \
	lineFollower.c
TOPPERS_OSEK_OIL_SOURCE = ./lineFollower.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
